server.error.include-stacktrace=never
server.error.include-exception=false

jwt.secret=Y2hhbmdlLXRoaXMtdG8tYS1yYW5kb20tMzItYnl0ZS1zZWNyZXQtMTIzNA==
jwt.access-token-expiration-ms=5000
jwt.refresh-token-expiration-ms=604800000